debug: True

mail_host: host
mail_port: 25 
mail_user: username
mail_pass: password
mail_from: local@localhost
admins:
 - mail@example.com

project_name: MINT
project_sub_name: BOS Manual Intervention Module
secret_key: RanDomSecrEtKeyStringusedInternallY

sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: Main
    Main:
        node:
         - wss://node.example.com

allowed_transitions:
    EventStatus:
        upcoming:
            - in_progress
            - finished
            - frozen
            - canceled
        in_progress:
            - finished
            - frozen
            - canceled
        finished:
            - settled
            - canceled
        frozen:
            - upcoming
            - in_progress
            - frozen
            - canceled
    BettingMarketGroupStatus:
        upcoming:
            - closed
            - canceled
            - in_play
            - frozen
        in_play:
            - frozen
            - closed
            - canceled
        closed:
            - graded
            - canceled
        graded:
            - re_grading
            - settled
            - canceled
        re_grading:
            - graded
            - canceled
    BettingMarketStatus:
        unresolved:
            - win
            - not_win
            - canceled
            - frozen
        frozen:
            - unresolved
            - win
            - not_win
            - canceled
        win:
            - not_win
            - canceled
        not_win:
            - canceled
            - win
