debug: True

secret_key: RUR7LywKvncb4eoR

connection:
    use: charlie
    
    charlie:
        node:
            - ws://ec2-35-183-1-21.ca-central-1.compute.amazonaws.com:8090
            - ws://ec2-54-93-87-186.eu-central-1.compute.amazonaws.com:8090
            - ws://ec2-54-252-139-217.ap-southeast-2.compute.amazonaws.com:8090
        nobroadcast: False
        num_retries: 1