debug: True

mail_host: host:port
mail_port: 25 
mail_user: username
mail_pass: password
mail_from: local@localhost
admins:
 - mail@xeroc.org

project_name: Bookie Oracle Software Suite
secret_key: RUR7LywKvncb4eoR

sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: Charlie
    Main:
        node:
            - 

    Test:
        node:
            - wss://peerplays-dev.blocktrades.info/ws
        nobroadcast: True
        num_retries: 1
        
    TestOSE:
        node:
            - wss://peerplays-dev.blocktrades.info/alpha/ws
        nobroadcast: False
        num_retries: 1

    Charlie:
        node:
         - ws://ec2-35-183-30-229.ca-central-1.compute.amazonaws.com:8090
        nobroadcast: False
        num_retries: 1
